# Generated by Django 5.0.2 on 2024-05-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuul_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('telegram_id', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
